# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant.require_version ">= 2"
# vagrant_api_version = "2"

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "bento/ubuntu-18.04"
NODE_COUNT = 2

$msg = <<MSG
------------------------------------------------------
Local Websphere, accessible at 127.0.0.1

URLS:
 - app under test  - http://localhost:8080/<app url>/
 - ibm console     - http://localhost:9060/ibm/console

------------------------------------------------------
MSG

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.post_up_message = $msg
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
    config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
    subconfig.vm.provision :shell, path: "bootstrap_master.sh"

    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "192.168.55.#{i + 10}"
      subconfig.vm.provision :shell, path: "bootstrap_node.sh"
    end
  end

end